## more info https://github.com/crazy-max/ghaction-github-labeler
- # antivirus
  name: ":space_invader: antivirus"
  color: "5c0493"
  description: ""
  from_name: "antivirus"
- # app request
  name: ":robot: app request"
  color: "28a745"
  description: ""
  from_name: "app-request"
- # bot
  name: ":robot: bot"
  color: "69cde9"
  description: ""
- # bug
  name: ":bug: bug"
  color: "b60205"
  description: ""
  from_name: "bug"
- # discontinued
  name: ":construction: discontinued"
  color: "f79307"
  description: ""
  from_name: "discontinued"
- # documentation
  name: ":memo: documentation"
  color: "c5def5"
  description: ""
  from_name: "doc"
- # duplicate
  name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: ""
  from_name: "duplicate"
- # enhancement
  name: ":sparkles: enhancement"
  color: "0054ca"
  description: ""
  from_name: "enhancement"
- # feature request
  name: ":bulb: feature request"
  color: "0e8a16"
  description: ""
- # feedback
  name: ":mega: feedback"
  color: "03a9f4"
  description: ""
- # future maybe
  name: ":rocket: future maybe"
  color: "fef2c0"
  description: ""
- # good first issue
  name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: ""
  from_name: "good first issue"
- # help wanted
  name: ":pray: help wanted"
  color: "4caf50"
  description: ""
  from_name: "help wanted"
- # hold
  name: ":hand: hold"
  color: "24292f"
  description: ""
- # invalid
  name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: ""
  from_name: "invalid"
- # maybe bug
  name: ":interrobang: maybe bug"
  color: "ff5722"
  description: ""
- # needs more info
  name: ":thinking: needs more info"
  color: "795548"
  description: ""
- # question
  name: ":question: question"
  color: "3f51b5"
  description: ""
  from_name: "question"
- # retained
  name: ":ok_hand: retained"
  color: "17a2b8"
  description: ""
  from_name: "retained"
- # upstream
  name: ":eyes: upstream"
  color: "fbca04"
  description: ""
- # wontfix
  name: ":coffin: wontfix"
  color: "ffffff"
  description: ""
  from_name: "wontfix"
